alias ls "ls -hN --color=auto --group-directories-first"
alias grep "grep --color=auto"
alias cp "cp -iv"
alias mv "mv -iv"
alias rm "rm -Iv"
alias diff "diff --color=auto"
alias ":q" "exit"
alias ":wq" "exit"
abbr cfg "git --git-dir=$HOME/.dots --work-tree=$HOME"
